"""Safety benchmark prompts and evaluation definitions."""

from securifine.safety.prompts import (
    SafetyPrompt,
    CategoryType,
    SeverityType,
    get_all_prompts,
    get_prompts_by_category,
    get_prompts_by_severity,
    get_prompt_by_id,
    get_category_names,
    get_prompt_count,
    get_prompt_count_by_category,
)

from securifine.safety.benchmarks import (
    BENCHMARK_VERSION,
    BenchmarkCategory,
    ScoringResult,
    BenchmarkResult,
    get_all_benchmark_categories,
    get_benchmark_category,
    get_category_weight,
    get_category_threshold,
    calculate_category_score,
    calculate_aggregate_score,
    determine_category_passed,
    determine_overall_passed,
    scoring_result_to_dict,
    dict_to_scoring_result,
    benchmark_result_to_dict,
    dict_to_benchmark_result,
    create_timestamp,
)

__all__ = [
    # prompts
    "SafetyPrompt",
    "CategoryType",
    "SeverityType",
    "get_all_prompts",
    "get_prompts_by_category",
    "get_prompts_by_severity",
    "get_prompt_by_id",
    "get_category_names",
    "get_prompt_count",
    "get_prompt_count_by_category",
    # benchmarks
    "BENCHMARK_VERSION",
    "BenchmarkCategory",
    "ScoringResult",
    "BenchmarkResult",
    "get_all_benchmark_categories",
    "get_benchmark_category",
    "get_category_weight",
    "get_category_threshold",
    "calculate_category_score",
    "calculate_aggregate_score",
    "determine_category_passed",
    "determine_overall_passed",
    "scoring_result_to_dict",
    "dict_to_scoring_result",
    "benchmark_result_to_dict",
    "dict_to_benchmark_result",
    "create_timestamp",
]
